### PR TITLE
Fixes v.2

### PR DESCRIPTION
**Pull request by VVWVV**

### CODE REVIEW

**Comment by Ino-Bagaric** [comment]
change '0 == var' to '!var' because compiler giving errors, thats boolean

**Comment by Ino-Bagaric** [comment]
also i test and now foreach doesnt working

**Comment by VVWVV** [comment]
Opsss.... I forgot.. :smile: I'm apologize.

**Comment by Ino-Bagaric** [comment]
foreach still buggy - [CreatePlayerProgressBar] ERROR: MAX_PLAYER_BARS limit reached.

**Comment by VVWVV** [comment]
Without foreach?

**Comment by Ino-Bagaric** [comment]
with foreach

**Comment by VVWVV** [comment]
what happens when foreach isn't included?

**Comment by Ino-Bagaric** [comment]
Then everything working

**Comment by Ino-Bagaric** [comment]
fill foreach from current released commit from my git, there working

**Comment by VVWVV** [comment]
This is a problem in progress2 library, because it uses foreach library.

**Comment by Ino-Bagaric** [comment]
Probably, but this from my current commit working perfect with foreach and without, just take all foreachs from here https://github.com/Ino42O/OxygenController/blob/master/OxygenController.inc
and send commit.. :)

**Comment by VVWVV** [comment]
My English today is bad (I'm sorry). I restore everything?

**Comment by Ino-Bagaric** [comment]
i just trying say that.. your current code style is good, and working, just don't working foreach, BUT if you take all codes about foreach from here ( https://github.com/Ino42O/OxygenController/blob/master/OxygenController.inc ) and implement it in your current commit that will work perfect

**Comment by VVWVV** [comment]
Thank you! Ok!

**Comment by Ino-Bagaric** [comment]
Thank you. :+1:

**Pull request merged**
